from __future__ import annotations
import pyimgui.gUtils
import pyimgui.imgui
import typing
__all__ = ['Begin', 'BeginChild', 'BeginChildEx', 'BeginColumns', 'BeginCombo', 'BeginDisabled', 'BeginDragDropSource', 'BeginDragDropTarget', 'BeginGroup', 'BeginItemTooltip', 'BeginListBox', 'BeginMainMenuBar', 'BeginMenu', 'BeginMenuBar', 'BeginPopup', 'BeginPopupModal', 'BeginTabBar', 'BeginTabItem', 'BeginTable', 'BeginTooltip', 'PushButtonRepeat', 'PushFont', 'PushID', 'PushItemWidth', 'PushStyleColor', 'PushStyleVar', 'PushTabStop', 'PushTextWrapPos']
def Begin(name: str = '', open: bool = True, flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def BeginChild(str_id: str, size: pyimgui.imgui.ImVec2 = ..., child_flags: int = 0, window_flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def BeginChild(id: int, size: pyimgui.imgui.ImVec2 = ..., child_flags: int = 0, window_flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginChildEx(name: str, id: int, size_arg: pyimgui.imgui.ImVec2, child_flags: int, window_flags: int) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginColumns(str_id: str, count: int = -1, flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginCombo(label: str, preview_value: str, flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginDisabled(disabled: bool = True) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginDragDropSource(flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginDragDropTarget() -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginGroup() -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginItemTooltip() -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginListBox(label: str, size: pyimgui.imgui.ImVec2 = ...) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginMainMenuBar() -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginMenu(label: str, enabled: bool = True) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginMenuBar() -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginPopup(str_id: str, flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginPopupModal(name: str, p_open: bool, flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginTabBar(str_id: str, flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginTabItem(label: str, p_open: bool, flags: int = 0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginTable(str_id: str, columns: int, flags: int = 0, outer_size: pyimgui.imgui.ImVec2 = ..., inner_width: float = 0.0) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def BeginTooltip() -> pyimgui.gUtils.PyCtxWrapper:
    ...
def PushButtonRepeat(repeat: bool) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def PushFont(font: pyimgui.imgui.ImFont) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def PushID(str_id: str) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def PushID(str_id_begin: str, str_id_end: str) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def PushID(ptr_id: capsule) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def PushID(int_id: int) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def PushItemWidth(item_width: float) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def PushStyleColor(idx: int, col: int) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def PushStyleColor(idx: int, col: pyimgui.imgui.ImVec4) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def PushStyleVar(idx: int, val: float) -> pyimgui.gUtils.PyCtxWrapper:
    ...
@typing.overload
def PushStyleVar(idx: int, val: pyimgui.imgui.ImVec2) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def PushTabStop(tab_stop: bool) -> pyimgui.gUtils.PyCtxWrapper:
    ...
def PushTextWrapPos(wrap_local_pos_x: float) -> pyimgui.gUtils.PyCtxWrapper:
    ...
